# Generated by Django 4.2 on 2023-04-29 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupdevices',
            name='name_group',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='groupdevices',
            name='names',
            field=models.CharField(default='', max_length=255),
        ),
    ]
